@startuml

hide methods
hide circle

class KaliberFølgeseddel
{
    ID
    StartDato
    Status
    Navn
}

class Station
{
    ID
    Navn
    StartDato
    SlutDato 
    Status
    Bemærkning
    Bygningsnavn
}

class Medarbejder 
{
    ID
    Navn 
    StationsID
}

class Bygning
{
    Navn
    Sektion
}

Medarbejder "0..*" -- "1" Station : Arbejder ved
' A station instance is added to KaliberFølgeseddel the moment a component arrives at a station. Thus the relationship is many to one.
KaliberFølgeseddel "1..*" -- "1" Station : Fører historik
Station "1..*" -- "1" Bygning : Indeholder
@enduml
