@startuml

hide methods
hide circle
class KaliberFølgeseddel
{
    ID
    StartDato
    Status
    Historik
}

class Historik
{
    ID
    Gennemført
    StationsID
}

class Station
{
    ID
    Navn
    StartDato
    SlutDato 
    Status
    Bemærkning
    Bygningsnavn
}

class Medarbejder 
{
    ID
    Navn 
    StationsID
}

class Bygning
{
    Navn
    Sektion
}

Medarbejder "1..* " -- "1" Station
KaliberFølgeseddel "1  " -- "1..*  " Historik
Historik "1 " -- "1..* " Station
Station "1..* " -- "1 " Bygning
@enduml
