@startuml

left to right direction
title Objekt Model

rectangle "Bygning " #line:white;{
    (A1\n1) as (Bygning) 
}

rectangle "Medarbejder " #line:white;{
    (001\nBørge) as (Medarbejder) 
    (002\nHans) as (Medarbejder2) 
}
rectangle "Station " #line:white;{
    (26\nGalvanisering\n18-02-2026\n19-02-2026\nFærdig\nAlt gik godt) as (Station)
}
rectangle "Kaliber Følgeseddel " #line:white;{
    (3123\n18-02-2026\nSkæring\n26\n002\nFærdig) as (KaliberFølgeseddel)
    (3124\n17-02-2026\nSkæring\n25\n001\nFærdig) as (KaliberFølgeseddel2)
}

Medarbejder -- Station
Medarbejder2 -- Station
KaliberFølgeseddel -- Station
KaliberFølgeseddel2 -- Station
Station -- Bygning
@enduml
