@startuml
title SSD: Opret følgeseddel

actor ": Medarbejder" as Medarbejder
participant ": System" as System

Medarbejder -> System: Opret følgeseddel
System --> Medarbejder: Viser mulige deltyper(Forhjulskaliber, Baghjulskaliber, Bremsekaliber)

Medarbejder -> System: Vælg deltype(Forhjulskaliber, Baghjulskaliber, Bremsekaliber)
Medarbejder -> System: Indtast evt. bemærkning
alt Medarbejder vælger at annullere
    Medarbejder -> System: Annuller oprettelse    
    System --> Medarbejder: Returnér til start
else Medarbejder gemmer oprettelse

    System --> Medarbejder: KaliberID bliver genereret og returneret til aktøren
    System --> Medarbejder: FølgeSeddel bliver Genereret og returneret til aktøren med kaliberID og evt bemærkning
end

@enduml
