@startuml
title SSD: Opret følgeseddel

actor ": Medarbejder" as Medarbejder
participant ": System" as System

Medarbejder -> System: Opret følgeseddel
System --> Medarbejder: Vis deltyper

Medarbejder -> System: Vælg deltype
Medarbejder -> System: Indtast startinfo\n(startDato, status, bemærkning, stationID)

alt Medarbejder vælger at annullere
    Medarbejder -> System: Annuller oprettelse    
    System --> Medarbejder: Returnér til start
else Medarbejder bekræfter oprettelse
    Medarbejder -> System: opretFølgeseddel( deltype, startDato, status, bemærkning, stationID)

    System --> Medarbejder: KaliberID
    System --> Medarbejder: Generér FølgeSeddel
end

@enduml
